### ISSUE TITLE
Документация по использованию

### ISSUE THREAD

**Issue by danyahr** [Orianti/bmstu-latex-class#1]
Добрый день! Есть ли подробная инструкция, как этим можно воспользоваться? 
Я опирался на инструкции описанные в следующих репозиториях, но не хватает понимания, как это настроить. Основная система - Windows 10, но могу настроить все и в linux (WSL 2 Ubuntu)
https://github.com/latex-g7-32/latex-g7-32
https://github.com/Korogodin/NSLReport

Заранее спасибо

**Comment by Orianti** [comment]
Подробная инструкция в разработке.

С чем именно возникают проблемы? С установкой дистрибутивов LaTeX (TeX Live, MiKTeX), текстовыми редакторами или установкой класса?

**Comment by danyahr** [comment]
Добрый день!
Спасибо за ответ. На данный момент с основными проблемами я разобрался. Оставлю свои заметки. 

1) Другие похожие проекты

https://github.com/latex-g7-32/latex-g7-32
https://github.com/Korogodin/NSLReport
https://github.com/CatInCosmicSpace/latex-template

Первый в целом про шаблон под ГОСТ7.32 на latex. Второй- это доработка лаборатории навигационных систем МЭИ. Третий - это доработка кафедры ИУ 8, пакеты выложены на CTAN, их можно скачать. 

2) Установка

2.1) Установка в Linux (через WSL2 на Windows 10)

Установить пакеты 
```  
sudo apt-get install -y \
            make \
            inkscape \
            imagemagick \            
            latexmk \
            texlive-latex-base \
            texlive-latex-extra \
            texlive-extra-utils \
            texlive-lang-cyrillic \
            texlive-luatex \ 
            texlive-bibtex-extra \
            biber \
            cm-super \
            python
```
Добавить в директорию template небольшой скрипт python
```
#!/usr/bin/python

import subprocess, sys

commands = [
    ['pdflatex', sys.argv[1] + '.tex'],
    ['biber', sys.argv[1]],
    ['pdflatex', sys.argv[1] + '.tex'],
    ['pdflatex', sys.argv[1] + '.tex']
]

for c in commands:
    subprocess.call(c)
```
Скопировать класс в папку
`cp -R bmstu ~/texmf/tex/latex/`

Запуск сборки файла 
` python3 name_of_script.py thesis`

Если возникнут дополнительные ошибки, искать причину в google. 

2.2) Установка на windows

Скачать [miktex](https://miktex.org/), установить редактор tex файлов. Я выбрал [texstudio](https://www.texstudio.org/). 
Далее необходимо перенести классы в нужные папки. Проверяем в MiKTeX –> Setting–> Directories пути. Добавляем в папку bmstu и обновляем БД. Тут у меня возникли некоторые трудности, в списке пакетов локальный так и не появился, но после добавления ошибки ушли.

**Comment by Orianti** [comment]
Вообще можно в любом случае рекомендовать установку редактора, такого как TeXstudio, любым другим способам использования шаблона.

TeXstudio по умолчанию уже готов к сборке проекта. Остается только установить TeX Live или MiKTeX. Я бы рекомендовал TeX Live вне зависимости от того, работаете вы под Windows или Linux ([подробнее](https://tex.stackexchange.com/questions/20036/what-are-the-advantages-of-tex-live-over-miktex)).

В будущем добавлю более подробную инструкцию по работе.

**Comment by Orianti** [comment]
Что касается пункта про похожие проекты. Этот был создан с целью стать универсальным: оформление по ГОСТ и по требованиям МГТУ, простое прохождение проверки TestVKR, простой интерфейс взаимодействия с классом, добавление команд для упрощения работы с ресурсами, создание титульных страниц всех типов работ.
