### ISSUE TITLE
Почему нет примера библиографии на русском?

### ISSUE THREAD

**Issue by Evgeniy-02** [Orianti/bmstu-latex-class#10]

**Comment by Evgeniy-02** [comment]
```

\documentclass{bmstu}

\begin{document}

Cite test \cite{kkk};

\begin{thebibliography}{00}

\bibitem{kkk} Some text

\end{thebibliography}

\end{document}


```

Подскажите, пожалуйста, почему ссылки на библиографию отображаются названиями, а не цифрами?

**Comment by Orianti** [comment]
Для сборки библиографии необходимо использовать biber, а не bibtex. К сожалению, используемый стиль библиографии [Biblatex-GOST](https://ctan.math.illinois.edu/macros/latex/contrib/biblatex-contrib/biblatex-gost/doc/biblatex-gost.pdf) работает только с biber.

Подробнее о разнице между biber и bibtex [тут](https://tex.stackexchange.com/questions/25701/bibtex-vs-biber-and-biblatex-vs-natbib).

Если необходимо использовать именно bibtex, можно переопределить настройку библиографии:
```latex
\usepackage[
	style=gost-numeric,  % Здесь использовать другой стиль.
	language=auto,
	autolang=other,
	sorting=none,
]{biblatex}
```
