### ISSUE TITLE
Формат бумаги

### ISSUE THREAD

**Issue by wcdbmv** [Orianti/bmstu-latex-class#4]
Шаблон на версии 1.0.0 может выдавать pdf-ки со страницами в формате US Letter (215.9×279.4 мм), если указана такая настройка по умолчанию.
ГОСТ 7.32-2017 требует A4 (п. 6.1.1)

**Comment by ermakov-dmitry** [comment]
Лечится так: \LoadClass[a4paper, 14pt]{extreport} в файле bmstu.cls

**Comment by Orianti** [comment]
> Лечится так: \LoadClass[a4paper, 14pt]{extreport} в файле bmstu.cls

Исправлено в b5900a99248b3cd0dc9c180fb4fa1ef59cb9e314.

**Comment by Tulenien** [comment]
Для сборки использую latex из texlive (полная установка) x86_64-linux. Установил класс из CTAN. При компиляции выдается страница формата letter. Исправил только установкой параметров страницы.
\pdfpageheight=11in
\pdfpagewidth=8.5in
