### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by danyahr** [Orianti/bmstu-latex-class#5]
Добрый день!
При использовании блока \begin{landscape} нумерация страницы остается в нижней части, хотя должна быть справа.  Есть ли понимание, как это исправить?

![image](https://user-images.githubusercontent.com/41299953/171414548-473dd49b-138a-4850-b954-0d62600aadef.png)

**Comment by Orianti** [comment]
Хоть требования к РПЗ и содержат пример с нумерацией страницы справа, при попытке проверить такой документ с помощью TestVKR появляется ошибка о выходе за поля. Это нужно иметь в виду.

Переместить номер страницы можно, но (судя по информации [здесь](https://tex.stackexchange.com/questions/278113/single-landscape-page-with-page-number-at-the-bottom) и [здесь](https://tex.stackexchange.com/questions/472937/how-can-i-bring-the-page-number-to-the-bottom-in-the-landscape-environment)) задача нетривиальная. Да и не ясно, как в таком случае проходить проверку.

Когда найду свободное время, проверю еще раз, как ведет себя TestVKR, если видит страницу в альбомное ориентации.

**Comment by Orianti** [comment]
Проверку TestVKR с такой нумерацией страниц в альбомной ориентации пройти не выйдет. Вынужден оставить как есть.
