### ISSUE TITLE
Список литературы

### ISSUE THREAD

**Issue by Perceivery** [Orianti/bmstu-latex-class#9]
Не совсем понимаю, как добавить список литературы. Вызываю команду \makebibliography , а куда вводить источники?

**Comment by Evgeniy-02** [comment]
> Не совсем понимаю, как добавить список литературы. Вызываю команду \makebibliography , а куда вводить источники?

Посмотрите инструкцию по использованию biblatex.
https://www.overleaf.com/learn/latex/Bibliography_management_with_biblatex

В преамбулу нужно вставить \bibliography{bibliography}, где bibliography - указатель на файл bibliography.bib
В документ нужно вставить \makebibliography в место, где необходимо отобразить список литературы.
bibliography.bib наполняется литературными источниками, к примеру:
@article{greenwade93,
    author  = "George D. Greenwade",
    title   = "The {C}omprehensive {T}ex {A}rchive {N}etwork ({CTAN})",
    year    = "1993",
    journal = "TUGBoat",
    volume  = "14",
    number  = "3",
    pages   = "342--351"
}

**Comment by Orianti** [comment]
Если ссылки на источники отображаются некорректно, убедитесь, что используете biber, а не bibtex. Подробнее: https://github.com/Orianti/bmstu-latex-class/issues/10.
